Improve preflight conditions

diff --git a/inst/workflows/docker_pr_receive.yaml b/inst/workflows/docker_pr_receive.yaml
--- a/inst/workflows/docker_pr_receive.yaml
+++ b/inst/workflows/docker_pr_receive.yaml
@@ -1,4 +1,4 @@
-name: "Receive Pull Request"
+name: "Bot: Receive Pull Request"
 
 on:
   pull_request:
@@ -14,24 +14,47 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+
+  preflight:
+    name: "Preflight: md-outputs exists?"
+    runs-on: ubuntu-latest
+    outputs:
+      branch-exists: ${{ steps.check.outputs.exists }}
+    steps:
+      - name: "Check if md-outputs branch exists"
+        id: check
+        run: |
+          if git ls-remote --exit-code --heads origin md-outputs; then
+            echo "exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "exists=false" >> $GITHUB_OUTPUT
+            echo "❌ md-outputs branch required. Please merge any open package update PRs, and run the '03 Maintain: Apply Package Cache' and '01: Maintain: Build and Deploy Site' workflows."
+            exit 1
+          fi
+
   test-pr:
     name: "Record PR number"
-    if: ${{ github.event.action != 'closed' }}
+    if: ${{ github.event.action != 'closed' }} && ${{ needs.preflight.outputs.branch-exists == 'true' }}
     runs-on: ubuntu-latest
+    needs: preflight
     outputs:
       is_valid: ${{ steps.check-pr.outputs.VALID }}
     steps:
-      - name: "Auto: Grab PR number"
+      - name: "Auto: Grab PR"
         if: ${{ github.event_name == 'pull_request' }}
         run: |
-          echo ${{ github.event.number }} > ${{ github.workspace }}/NR # 2022-03-02: artifact name fixed to be NR
+          echo ${{ github.event.number }} > ${{ github.workspace }}/NR
           echo "NR=${{ github.event.number }}" >> $GITHUB_ENV
+          echo "PR_BRANCH=main" >> $GITHUB_ENV
 
-      - name: "Manual: Grab PR number"
+      - name: "Manual: Grab PR"
         if: ${{ github.event_name == 'workflow_dispatch' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo ${{ inputs.pr_number }} > ${{ github.workspace }}/NR
           echo "NR=${{ inputs.pr_number }}" >> $GITHUB_ENV
+          echo "PR_BRANCH=$(gh -R ${{ github.repository }} pr view ${{ env.NR }} --json headRefName --jq '.headRefName')" >> $GITHUB_ENV
 
       - name: "Upload PR number"
         id: upload
@@ -56,11 +79,11 @@ jobs:
         id: check-pr
         uses: carpentries/actions/check-valid-pr@main
         with:
-          pr: ${{ github.event.number }}
+          pr: ${{ env.NR }}
           invalid: ${{ fromJSON(steps.hash.outputs.json)[github.repository] }}
 
   check-renv:
-    name: "Check if We Need {renv}"
+    name: "Check If We Need {renv}"
     runs-on: ubuntu-latest
     outputs:
       renv-needed: ${{ steps.check-for-renv.outputs.exists }}
@@ -117,6 +140,8 @@ jobs:
     steps:
       - name: "Check Out Main Branch"
         uses: actions/checkout@v4
+        with:
+          ref: ${{ env.PR_BRANCH }}
 
       - name: "Check Out Staging Branch"
         uses: actions/checkout@v4
